version: '3.8'

services:
  integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: woocommerce-erpnext-integration

    working_dir: /code
    volumes:
      - ./:/code

    env_file:
      - .env
    command: [ "uvicorn", "app.main_app:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers" ]

    ports:
      - "8000:8000"

    labels:
      - "traefik.enable=true"

      # admin pages
      - "traefik.http.routers.integration-admin.rule=Host(`records.techniclad.co.za`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.integration-admin.entrypoints=websecure"
      - "traefik.http.routers.integration-admin.tls.certresolver=main-resolver"

      # static assets
      - "traefik.http.routers.integration-static.rule=Host(`records.techniclad.co.za`) && PathPrefix(`/static`)"
      - "traefik.http.routers.integration-static.entrypoints=websecure"
      - "traefik.http.routers.integration-static.tls.certresolver=main-resolver"

    networks:
      - frappe_default
    restart: unless-stopped

networks:
  frappe_default:
    external: true
